# Generated by Django 3.0.2 on 2021-04-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deliveries',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileupload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
