# Generated by Django 3.0.2 on 2021-05-03 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210503_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
