# Generated by Django 3.0.2 on 2021-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210503_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
