# Generated by Django 3.0.2 on 2021-05-03 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210503_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientareas',
            name='client',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Clients'),
        ),
        migrations.AlterField(
            model_name='clientareas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
