# Generated by Django 3.0.2 on 2021-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210503_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientareas',
            name='area_name',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
