# Generated by Django 3.0.2 on 2021-05-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210503_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientareas',
            name='client',
        ),
        migrations.AlterField(
            model_name='clientareas',
            name='area_name',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ClientAreas'),
        ),
    ]
