# Generated by Django 3.0.2 on 2021-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20210503_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
