# Generated by Django 3.0.2 on 2021-05-04 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_auto_20210503_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientareas',
            name='area',
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
