# Generated by Django 3.0.2 on 2021-05-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20210504_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.UUIDField(),
        ),
    ]
