# Generated by Django 3.0.2 on 2021-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20210504_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientareas',
            name='area_name',
            field=models.UUIDField(),
        ),
    ]
