# Generated by Django 3.0.2 on 2021-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20210504_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientareas',
            name='area_name',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
