# Generated by Django 3.0.2 on 2021-05-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20210504_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientareas',
            name='area',
        ),
    ]
