# Generated by Django 3.0.2 on 2021-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_remove_clientareas_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientareas',
            name='area_name',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
