# Generated by Django 3.0.2 on 2021-05-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_auto_20210504_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientareas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Clients'),
        ),
        migrations.AlterField(
            model_name='clientareas',
            name='area_name',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
