# Generated by Django 3.0.2 on 2021-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_auto_20210504_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientareas',
            name='area',
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
