# Generated by Django 3.0.2 on 2021-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_auto_20210504_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientareas',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
