# Generated by Django 3.0.2 on 2021-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_auto_20210504_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
